services:
  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"] 
      interval: 5s                    
      timeout: 2s                     
      retries: 5                      
    networks:
      - app-network
    restart: always

  app1:
    build: .
    env_file:
      - ./.env 
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge